import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

final TextTheme lightTextTheme = TextTheme(
  displayLarge: TextStyle(
    fontFamily: 'Outfit',
    color: Colors.black87,
    fontSize: 57.sp,
    fontWeight: FontWeight.w300,
    letterSpacing: -1.5,
  ),
  displayMedium: TextStyle(
    fontFamily: 'Outfit',
    color: Colors.black87,
    fontSize: 45.sp,
    fontWeight: FontWeight.w300,
    letterSpacing: -0.5,
  ),
  displaySmall: TextStyle(
    fontFamily: 'Outfit',
    color: Colors.black87,
    fontSize: 36.sp,
    fontWeight: FontWeight.w400,
    letterSpacing: 0,
  ),
  headlineLarge: TextStyle(
    fontFamily: 'Outfit',
    color: Colors.black87,
    fontSize: 32.sp,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.25,
  ),
  headlineMedium: TextStyle(
    fontFamily: 'Outfit',
    color: Colors.black87,
    fontSize: 28.sp,
    fontWeight: FontWeight.w400,
    letterSpacing: 0,
  ),
  headlineSmall: TextStyle(
    fontFamily: 'Outfit',
    color: Colors.black87,
    fontSize: 24.sp,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.15,
  ),
  titleLarge: TextStyle(
    fontFamily: 'Outfit',
    color: Colors.black87,
    fontSize: 22.sp,
    fontWeight: FontWeight.bold,
    letterSpacing: 0.15,
  ),
  titleMedium: TextStyle(
    fontFamily: 'Outfit',
    color: Colors.black87,
    fontSize: 16.sp,
    fontWeight: FontWeight.bold,
    letterSpacing: 0.1,
  ),
  titleSmall: TextStyle(
    fontFamily: 'Outfit',
    color: Colors.black,
    fontSize: 14.sp,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.1,
  ),
  bodyLarge: TextStyle(
    fontFamily: 'Outfit',
    color: const Color(0xFF292D32),
    fontSize: 17.sp,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.5,
  ),
  bodyMedium: TextStyle(
    fontFamily: 'Outfit',
    color: const Color(0xFF292D32),
    fontSize: 15.sp,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.25,
  ),
  bodySmall: TextStyle(
    fontFamily: 'Outfit',
    color: const Color(0xFF46505D),
    fontSize: 13.sp,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.4,
  ),
  labelLarge: TextStyle(
    fontFamily: 'Outfit',
    color: const Color(0xFF292D32),
    fontSize: 14.sp,
    fontWeight: FontWeight.w400,
    // letterSpacing: 1.5,
  ),
  labelMedium: TextStyle(
    fontFamily: 'Outfit',
    color: const Color(0xFF292D32),
    fontSize: 12.sp,
    fontWeight: FontWeight.w500,
    // letterSpacing: 1.5,
  ),
  labelSmall: TextStyle(
    fontFamily: 'Outfit',
    color: const Color(0xFF46505D),
    fontSize: 11.sp,
    fontWeight: FontWeight.w400,
    // letterSpacing: 1.5,
  ),
);

final TextTheme darkTextTheme = TextTheme(
  displayLarge: TextStyle(
    fontFamily: 'Outfit',
    color: Colors.white,
    fontSize: 57.sp,
    fontWeight: FontWeight.w300,
    letterSpacing: -1.5,
  ),
  displayMedium: TextStyle(
    fontFamily: 'Outfit',
    color: Colors.white,
    fontSize: 45.sp,
    fontWeight: FontWeight.w300,
    letterSpacing: -0.5,
  ),
  displaySmall: TextStyle(
    fontFamily: 'Outfit',
    color: Colors.white,
    fontSize: 36.sp,
    fontWeight: FontWeight.w400,
    letterSpacing: 0,
  ),
  headlineLarge: TextStyle(
    fontFamily: 'Outfit',
    color: Colors.white,
    fontSize: 32.sp,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.25,
  ),
  headlineMedium: TextStyle(
    fontFamily: 'Outfit',
    color: Colors.white,
    fontSize: 28.sp,
    fontWeight: FontWeight.w400,
    letterSpacing: 0,
  ),
  headlineSmall: TextStyle(
    fontFamily: 'Outfit',
    color: Colors.white,
    fontSize: 24.sp,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.15,
  ),
  titleLarge: TextStyle(
    fontFamily: 'Outfit',
    color: Colors.white,
    fontSize: 22.sp,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.15,
  ),
  titleMedium: TextStyle(
    fontFamily: 'Outfit',
    color: Colors.white,
    fontSize: 16.sp,
    fontWeight: FontWeight.bold,
    letterSpacing: 0.1,
  ),
  titleSmall: TextStyle(
    fontFamily: 'Outfit',
    color: Colors.white,
    fontSize: 14.sp,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.1,
  ),
  bodyLarge: TextStyle(
    fontFamily: 'Outfit',
    color: Colors.white,
    fontSize: 16.sp,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.5,
  ),
  bodyMedium: TextStyle(
    fontFamily: 'Outfit',
    color: Colors.white,
    fontSize: 14.sp,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.25,
  ),
  bodySmall: TextStyle(
    fontFamily: 'Outfit',
    color: Colors.white,
    fontSize: 12.sp,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.4,
  ),
  labelLarge: TextStyle(
    fontFamily: 'Outfit',
    color: Colors.white,
    fontSize: 14.sp,
    fontWeight: FontWeight.w400,
    // letterSpacing: 1.5,
  ),
  labelMedium: TextStyle(
    fontFamily: 'Outfit',
    color: Colors.white,
    fontSize: 12.sp,
    fontWeight: FontWeight.w500,
    // letterSpacing: 1.5,
  ),
  labelSmall: TextStyle(
    fontFamily: 'Outfit',
    color: Colors.white,
    fontSize: 11.sp,
    fontWeight: FontWeight.w400,
    // letterSpacing: 1.5,
  ),
);
